version: '3.2'
services:
#  legacywebshop:
#    build:
#      context: ./
#      dockerfile: ./docker/Dockerfile
#    ports:
#      - "8888:8080"
#    networks:
#      local_dev_net:
#          aliases:
#              - legacywebshop

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image
    
  web-shop-db-image-category:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQLCategory
    volumes:
      - "./.data/db1:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: category
      MYSQL_USER: categoryUser
      MYSQL_PASSWORD: categoryPassword
    ports:
      - "3307:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image-category
  
  web-shop-db-image-product:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQLProduct
    volumes:
      - "./.data/db2:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: product
      MYSQL_USER: productUser
      MYSQL_PASSWORD: productPassword
    ports:
      - "3308:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image-product
  
  web-shop-microservice-category:
    build:
      context: ./microservices/CategoryService
      dockerfile: ./Dockerfile
    ports:
      - "8889:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://web-shop-db-image-category:3306/category
    networks:
      local_dev_net:
          aliases:
              - microservicecategory

  web-shop-microservice-product:
    build:
      context: ./microservices/ProductService
      dockerfile: ./Dockerfile
    ports:
      - "8890:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://web-shop-db-image-product:3306/product
    networks:
      local_dev_net:
        aliases:
          - microserviceproduct

networks:
  local_dev_net:
    driver: bridge
